RS1_Ispit_2017_01_24_aspnet_core/RS1_PrakticniDioIspita_2017_01_24/Controllers/CasoviController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RS1_PrakticniDioIspita_2017_01_24.EF;
using RS1_PrakticniDioIspita_2017_01_24.Helper;
using RS1_PrakticniDioIspita_2017_01_24.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using RS1_PrakticniDioIspita_2017_01_24.Models;
using Microsoft.EntityFrameworkCore;

namespace RS1_PrakticniDioIspita_2017_01_24.Controllers
{
    public class CasoviController : Controller
    {
        private MojContext _context;

        public CasoviController(MojContext db)
        {
            _context = db;
        }
        public IActionResult Index()
        {
            NastavnikLoginVM logiraniNastavnik = HttpContext.GetLogiraniKorisnik();
            if (logiraniNastavnik == null)
            {
                RedirectToAction("Index", "Login");
            }

            var model = new CasoviIndexVM
            {
                Redovi = _context.OdrzaniCas.Where(w => w.Angazovan.NastavnikId == logiraniNastavnik.NastavnikId).Select(s => new CasoviIndexVM.Red
                {
                    OdrzaniCasId = s.Id,
                    DatumOdrzanogCasa = s.Datum,
                    Odjeljenje = s.Angazovan.Odjeljenje.Oznaka,
                    BrojPrisutnih = _context.OdrzaniCasDetalj.Where(t => t.OdrzaniCasId == s.Id).Count(c => c.Odsutan == false).ToString() + " od " + _context.OdrzaniCasDetalj.Where(t => t.OdrzaniCasId == s.Id).Count().ToString(),
                    Predmet = s.Angazovan.Predmet.Naziv,
                    NajboljiUcenikNaPredmetu = _context.OdrzaniCasDetalj.Where(p => p.OdrzaniCasId == s.Id).OrderByDescending(o => o.Ocjena).Select(z => z.UpisUOdjeljenje.Ucenik.Ime).FirstOrDefault().ToString()
                }).ToList()
            };
            return View(model);
        }
        public IActionResult Dodaj()
        {
            NastavnikLoginVM logiraniNastavnik = HttpContext.GetLogiraniKorisnik();

            var model = new CasoviDodajVM
            {
                Datum = DateTime.Now,
                Angazovani = _context.Angazovan.Where(w => w.NastavnikId == logiraniNastavnik.NastavnikId).Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.Odjeljenje.Oznaka + " / " + s.Predmet.Naziv
                }).ToList()
            };
            return View(model);
        }

        public IActionResult Snimi(CasoviDodajVM input)
        {
            NastavnikLoginVM logiraniNastavnik = HttpContext.GetLogiraniKorisnik();

            if (!ModelState.IsValid)
            {
                input.Angazovani = _context.Angazovan.Where(w => w.NastavnikId == logiraniNastavnik.NastavnikId).Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.Odjeljenje.Oznaka + " / " + s.Predmet.Naziv
                }).ToList();

                return View("Dodaj", input);
            }

            OdrzaniCas ocs = _context.OdrzaniCas.Find(input.OdrzaniCasId);

            if (ocs != null)
            {
                ocs.Datum = input.Datum;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            OdrzaniCas oc = new OdrzaniCas
            {
                AngazovanId = input.AngazovaniId,
                Datum = input.Datum
            };
            _context.OdrzaniCas.Add(oc);
            _context.SaveChanges();

            //odjeljenje u kome je angozavan nastavnik
            var OdjeljenjeId = _context.Angazovan.Where(w => w.Id == input.AngazovaniId).Select(s => s.OdjeljenjeId).SingleOrDefault();

            var list = _context.UpisUOdjeljenje.Where(w => w.OdjeljenjeId == OdjeljenjeId).ToList();

            foreach (var x in list)
            {
                OdrzaniCasDetalj ocd = new OdrzaniCasDetalj
                {
                    OdrzaniCasId = oc.Id,
                    UpisUOdjeljenjeId = x.Id
                };
                _context.OdrzaniCasDetalj.Add(ocd);
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            OdrzaniCas oc = _context.OdrzaniCas.Where(w => w.Id == id).Include(i => i.Angazovan).ThenInclude(t => t.Odjeljenje).Include(i => i.Angazovan).ThenInclude(t => t.Predmet).SingleOrDefault();

            NastavnikLoginVM logiraniNastavnik = HttpContext.GetLogiraniKorisnik();

            var model = new CasoviDodajVM
            {
                Datum = oc.Datum,
                Angazovan = oc.Angazovan.Odjeljenje.Oznaka + " / " + oc.Angazovan.Predmet.Naziv,
                OdrzaniCasId = oc.Id
            };
            return View(model);
        }
    }
}

RS1_Ispit_2017_01_24_aspnet_core/RS1_PrakticniDioIspita_2017_01_24/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using RS1_PrakticniDioIspita_2017_01_24.Helper;
@using RS1_PrakticniDioIspita_2017_01_24.ViewModels;
@{
    NastavnikLoginVM username = Context.GetLogiraniKorisnik();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ispit_2017_09_11_DotnetCore</title>

    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="/css/site.css" />

    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/js/site.js"></script>
    <script src="/JFIT.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Ispit_2017_09_11_DotnetCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Casovi" asp-action="Index">Casovi</a></li>
                    <li>
                        <a asp-area="" asp-controller="Login" asp-action="Logout">
                            @if (username != null)
                            {
                                <label>
                                    @username.Username
                                    Logout
                                </label>

                            }
                            else
                            {
                                <label>
                                    Login
                                </label>
                            }
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Ispit_2017_09_11_DotnetCore</p>
        </footer>
    </div>
</body>
</html>